name: checkmate-server
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 4300:4300
    volumes:
      - ./conf:/app/conf
      - ./db:/app/db
      - ./documents:/documents
    restart: always
    
