root = "."
tmp_dir = "."

[build]
  bin = "./checkmate.exe"
  cmd = "go build -o ./checkmate.exe ."
  args_bin = []
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "./checkmate.exe"
  include_dir = ["cmd","core","gui","httpd","version"]
  include_ext = ["go", "tpl", "tmpl", "html", "json"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
