root = "."
tmp_dir = "tmp"

[build]
  bin = "server.exe"
  cmd = "go build -o tmp/server.exe ."
  args_bin = []
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "tmp/server.exe"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "json"]
  log = "build-errors.log"
  # It's not necessary to trigger build each time file changes if it's too frequent.
  delay = 1000 # ms
  # Stop running old binary when build errors occur.
  stop_on_error = true
  # Send Interrupt signal before killing process (windows does not support this feature)
  send_interrupt = false
  # Delay after sending Interrupt signal
  kill_delay = 1000 # ms

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true
